#!/bin/sh

echo "Running Checkstyle before commit..."

mvn checkstyle:check
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "Checkstyle failed. Commit aborted."
  exit 1
fi

echo "Checkstyle passed."
exit 0